### ISSUE TITLE
Simplify navigation

### ISSUE THREAD

**Issue by sibelius** [terrysahaidak/GitterMobile#32]
[react-native-router-flux](https://github.com/aksonov/react-native-router-flux) can make simpler your navigation, and it easy integrate with redux

**Comment by terrysahaidak** [comment]
Hey @sibeliusseraphini, 

I've tried that but haven't found it really useful for me. Navigation module now is just a temporary workaround to save my state inside the redux store. I'm still waiting for stable Experimental Navigator release. 

You can find my attempts to use it in the experimental-navigator branch. But it still has some performance issues with animation transitions.

**Comment by sibelius** [comment]
there are refactoring this module to use the experimental navigator, it will probably fixes this

**Comment by terrysahaidak** [comment]
The performance issue is the biggest reason I still use legacy navigator and this ~~crutch~~ workaround and still not already switched to experimental one.

**Comment by terrysahaidak** [comment]
Closes because of #88
