### ISSUE TITLE
Formatting issue in README

### ISSUE THREAD

**Issue by gamtiq** [terrysahaidak/GitterMobile#95]
There is a typo in `README.md` causing incorrect appearance of the following sentence:
> To run GitterMobile on iOS you need to open `ios/gittermobile.xcworkspace` instead of *ios/gittermobile.xcodeproj`* in Xcode.

**Comment by terrysahaidak** [comment]
Hey @gamtiq. Did you mean missing `?

**Comment by gamtiq** [comment]
Exactly.

**Comment by terrysahaidak** [comment]
@gamtiq, thank you :)
